### ISSUE TITLE
Config file does not exist: config.yml

### ISSUE THREAD

**Issue by lubaso** [eqasim-org/sao_paulo#7]
Trying to run the pipeline, I got this issue:

`(sao_paulo) Lucass-MacBook-Pro:resources lucaslbs$ open . 
(sao_paulo) Lucass-MacBook-Pro:resources lucaslbs$ python3 -m synpp
Traceback (most recent call last):
  File "/Users/lucaslbs/opt/anaconda3/envs/sao_paulo/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/lucaslbs/opt/anaconda3/envs/sao_paulo/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/lucaslbs/opt/anaconda3/envs/sao_paulo/lib/python3.7/site-packages/synpp/__main__.py", line 12, in <module>
    raise synpp.PipelineError("Config file does not exist: %s" % config_path)
synpp.general.PipelineError: Config file does not exist: config.yml`

Any thoughts on how to solve that?

**Comment by balacmi** [comment]
Are you running the pipeline from the directory where the config.yml file is located? I can see that the file is in the root of the repository.
