### ISSUE TITLE
Errors in synpp pipeline

### ISSUE THREAD

**Issue by mari-ohira** [eqasim-org/sao_paulo#8]
This showed up when I tried to run the synpp pipeline:

```
(sao_paulo) D:\MARI\__MESTRADO\EQASIM\sao_paulo>python -m synpp
INFO:synpp:Found 4 stages
INFO:synpp:Did not find pipeline metadata in D:\MARI\__MESTRADO\EQASIM\sao_paulo\cache/pipeline.json
Traceback (most recent call last):
  File "C:\Users\Mariana\Anaconda3\envs\sao_paulo\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Mariana\Anaconda3\envs\sao_paulo\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Mariana\Anaconda3\envs\sao_paulo\lib\site-packages\synpp\__main__.py", line 14, in <module>
    synpp.run_from_yaml(config_path)
  File "C:\Users\Mariana\Anaconda3\envs\sao_paulo\lib\site-packages\synpp\pipeline.py", line 751, in run_from_yaml
    run(definitions=definitions, config=config, working_directory=working_directory, flowchart_path=flowchart_path, dryrun=dryrun)
  File "C:\Users\Mariana\Anaconda3\envs\sao_paulo\lib\site-packages\synpp\pipeline.py", line 591, in run
    validation_token = stage["wrapper"].validate(context)
  File "C:\Users\Mariana\Anaconda3\envs\sao_paulo\lib\site-packages\synpp\pipeline.py", line 52, in validate
    return self.instance.validate(context)
  File "D:\MARI\__MESTRADO\EQASIM\sao_paulo\matsim\runtime\maven.py", line 39, in validate
    ], stderr = sp.STDOUT):
  File "C:\Users\Mariana\Anaconda3\envs\sao_paulo\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Users\Mariana\Anaconda3\envs\sao_paulo\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Mariana\Anaconda3\envs\sao_paulo\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Mariana\Anaconda3\envs\sao_paulo\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the specified file
```

Any thoughts on how to solve this?

**Comment by balacmi** [comment]
Hey Mari,

You are missing the maven on your system, or it is not on the system path. As an alternative you can also provide the path in the config.yml file in the following way:

`maven_binary: "path-to-maven/bin/mvn"`

I hope this helps you out.

**Comment by mari-ohira** [comment]
Hi Milos,

I installed Maven and put it in the system path, but somehow synpp doesn't recognise it. Your workaround to put the path in the config file worked perfectly. Thank you!
