### ISSUE TITLE
Error running sao_paulo

### ISSUE THREAD

**Issue by mari-ohira** [eqasim-org/sao_paulo#9]
I was able to run île-de-france, but sao_paulo isn't working:

```
(sao_paulo) D:\MARI\__MESTRADO\EQASIM\sao_paulo>python -m synpp
INFO:numexpr.utils:Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
SQLalchemy is not installed. No support for SQL output.
INFO:synpp:Found 31 stages
INFO:synpp:Did not find pipeline metadata in D:\MARI\__MESTRADO\EQASIM\sao_paulo\cache/pipeline.json
Traceback (most recent call last):
  File "C:\Users\Mariana\Anaconda3\envs\sao_paulo\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Mariana\Anaconda3\envs\sao_paulo\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Mariana\Anaconda3\envs\sao_paulo\lib\site-packages\synpp\__main__.py", line 14, in <module>
    synpp.run_from_yaml(config_path)
  File "C:\Users\Mariana\Anaconda3\envs\sao_paulo\lib\site-packages\synpp\pipeline.py", line 751, in run_from_yaml
    run(definitions=definitions, config=config, working_directory=working_directory, flowchart_path=flowchart_path, dryrun=dryrun)
  File "C:\Users\Mariana\Anaconda3\envs\sao_paulo\lib\site-packages\synpp\pipeline.py", line 591, in run
    validation_token = stage["wrapper"].validate(context)
  File "C:\Users\Mariana\Anaconda3\envs\sao_paulo\lib\site-packages\synpp\pipeline.py", line 52, in validate
    return self.instance.validate(context)
  File "D:\MARI\__MESTRADO\EQASIM\sao_paulo\matsim\runtime\maven.py", line 39, in validate
    ], stderr = sp.STDOUT):
  File "C:\Users\Mariana\Anaconda3\envs\sao_paulo\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Users\Mariana\Anaconda3\envs\sao_paulo\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Mariana\Anaconda3\envs\sao_paulo\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Mariana\Anaconda3\envs\sao_paulo\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
PermissionError: [WinError 5] Denied Access
```
Any idea what could be wrong?

**Comment by balacmi** [comment]
To me it looks like windows denied access to the file you are trying to read. It should not have anything to do with the pipeline itself according to the error provided at the bottom of your message.
